Cc compare spectra
AI-multimodal/Lightshow pull request #242
Opened 2024-02-20 17:05 UTC by chuntian236

Created "compare_utils.py" for spectra comparison and alignment: 
https://github.com/AI-multimodal/Lightshow/blob/cc-compare-spectra/lightshow/postprocess/compare_utils.py

Jupyter notebook: 
https://github.com/AI-multimodal/Lightshow/blob/cc-compare-spectra/notebooks/compare_spectra.ipynb

2024-02-21 13:14 UTC, matthewcarbone requested changes
Overall very nice. Just a few nitpicks then I can merge. Thanks!

2024-02-21 13:14 UTC, matthewcarbone commented on lightshow/postprocess/compare_utils.py
> +def CosSimilar(v1, v2):
Minor ask here, can we make the function styles consistent? I.e., this should be `cos_similar`.

2024-02-21 13:14 UTC, matthewcarbone commented on lightshow/postprocess/compare_utils.py
> +def maxCorr(
Similar, this should be `max_corr`.

2024-02-21 13:14 UTC, matthewcarbone commented on lightshow/postprocess/compare_utils.py
> +    spectrum1, spectrum2, omega=0, GRID=None, verbose=True, method="all"
All caps are generally reserved for globals. Can we change `GRID` to `grid`?

2024-02-22 13:55 UTC, matthewcarbone requested changes
I think the code looks good but we need to improve the documentation here a bit more. Docs should follow the [NumPy style](https://numpydoc.readthedocs.io/en/latest/format.html). @chuntian236, do you want to do this here or should we just open an issue and do it later?

2024-02-22 14:24 UTC, chuntian236 commented
> I think the code looks good but we need to improve the documentation here a bit more. Docs should follow the [NumPy style](https://numpydoc.readthedocs.io/en/latest/format.html). @chuntian236, do you want to do this here or should we just open an issue and do it later?

Let me try to do this here. I might forget everything if I decide to do it later.

2024-02-25 05:02 UTC, matthewcarbone approved these changes
This is way better. Some nitpicks here and there but honestly I don't really mind merging at this stage.

2024-02-25 05:03 UTC, merged